### PR TITLE
ELB Policies Added

### PR DESCRIPTION
**Pull request by dhruv-aws**
The template was failing to create with an error 'ELB Listener Policy does not exist'

Created the policy and it works fine. 

Please do check the Attributes Name and Value. 
------

      Policies:
        - PolicyName: JSessionIdStickiness
          PolicyType: AppCookieStickinessPolicyType
          Attributes:
           - "Name" : CookieName
             "Value" : JSESSIONID
        - PolicyName: SessionStickiness
          PolicyType: AppCookieStickinessPolicyType
          Attributes:
           - "Name" : CookieName
             "Value" : BITBUCKETSESSIONID
------

### CODE REVIEW

**Comment by avattathil** [comment]
@kamarja  please run this branch in taskcat and make sure the endpoint comes up.  I will contact Atlassian to review the pull from an application perspective once that is complete thanks

**Comment by CensoredUser** [comment]
We've resolved this issue in our templates in [this pull request on Bitbucket](https://bitbucket.org/atlassian/atlassian-aws-deployment/pull-requests/59). I was going to raise a pull request for this here today. 

I've raised pull request #12, which has the "right" fix for this issue, as well as updates the AMI to the latest version.

**Comment by avattathil** [comment]
Ok I will merge #12  and have @dhruv-aws verify that the issues are solved

**Comment by kamarja** [comment]
I get the error below during the launch process. The AppCookieStickinessPolicy property will create a policy called SessionStickiness. Specifying the SessionStickiness policy again under Policies causes an error. It launches if the second entry is removed.

CREATE_FAILED
AWS::ElasticLoadBalancing::LoadBalancer 
Duplicate policy name: SessionStickiness found

**Comment by avattathil** [comment]
Pull #12 Resolves this issue

**Pull request closed without merging**
