### PR TITLE
Update AMIs to upgrade Postgres version to 9.6

### PR DESCRIPTION
**Pull request by alibk0rd**
We decommissioned Postgres 9.3 in Bitbucket Server 6.x (about to be released soon), but the AMIs still had the Postgres version set to 9.3 so our templates won't work with BbS 6.0 and above. This change upgrades the Postgres version to 9.6.

### CODE REVIEW

**Comment by avattathil** [comment]
@nanux just confirming that these comments are obsolete with the new updates in develop

**Comment by avattathil** [comment]
Cleanup for release  _Please send PR to Upstream link_

**Contributing & issues**
Please note that issues are disabled for this repository as it is only a downstream repository that is not actively supported. **Pull requests**, **issues** and **comments** are welcomed in the  [upstream repository](https://bitbucket.org/atlassian/atlassian-aws-deployment/src/master/quickstarts/)

**Comment by alibk0rd** [comment]
These changes have already been merged into the [upstream repository](https://bitbucket.org/atlassian/atlassian-aws-deployment/pull-requests/260/bbsdev-19176-bumped-bitbucket-postgres/diff) in a separate PR, but they don't seem to have been applied here yet.
How often is this repository updated from the upstream?

**Comment by alibk0rd** [comment]
Created PR targeting the upstream repository: https://github.com/atlassian/quickstart-atlassian-bitbucket/pull/3

**Pull request closed without merging**
